from tempfile import TemporaryDirectory
from pathlib import Path

from pymobiledevice3.lockdown import create_using_usbmux
from pymobiledevice3.services.mobilebackup2 import Mobilebackup2Service
from pymobiledevice3.exceptions import PyMobileDevice3Exception
from pymobiledevice3.services.diagnostics import DiagnosticsService

from . import backup

def perform_restore(backup: backup.Backup, reboot: bool = False):
    try:
        with TemporaryDirectory() as backup_dir:
            backup.write_to_directory(Path(backup_dir))
                
            lockdown = create_using_usbmux()
            with Mobilebackup2Service(lockdown) as mb:
                mb.restore(backup_dir, system=True, copy=False, source=".")
    except PyMobileDevice3Exception as e:
        if "Find My" in str(e):
            print("Find My must be disabled in order to use this tool.")
            print("Disable Find My from Settings (Settings -> [Your Name] -> Find My) and then try again.")
            raise e
        elif "File Exists" in str(e):
            print("File already exists at the specified path. Consider removing or overwriting it before retrying.")
        elif "crash_on_purpose" not in str(e):
            raise e
        else:
            if reboot and lockdown != None:
                print("Success! Rebooting your device...")
                with DiagnosticsService(lockdown) as diagnostics_service:
                    diagnostics_service.restart()